app/lib/RouteResolver.js, test/integration/response-test.js
We only want the user to be able to send one response type at a time. With these
restrictions, we can assert that there is only one of the response prop types we
intend the user to have the the response object, at a time.
=> Add Route Options Validation

test/integration/middleware-test.js
Aims to resolve https://github.com/ryanricard/mockyeah/issues/11
This adds a small test that asserts that you can use the exposed `./app` directory
to implement middleware using mockyeah.
------------------------
Test 1
- Supertest directly calls the `app`, and validates middleware is exposed.
Test 2
- Supertest calls URL where mockyeah is running to validate that middleware has
been exposed.
=> Add Middleware Test

package.json, server/index.js
[cors](https://github.com/expressjs/cors) is an expressjs made middleware, for enabling CORS with various options.
Since we're using proxies for real services to record fixtures, if we want to be able to use those same endpoints while developing, we'll need to be able to allow users to have CORS enabled for all routes.
=> Add Express Middleware for CORS

config.js
Trap parsing of invalid .mockyeah configuration and throw useful error.
I manually tested with `test/dummy`... I have not yet figured out a way to write an automated test.
=> Trap invalid .mockyeah config

app/lib/RouteResolver.js, test/integration/ResponseValidationTest.js
When users are beginning to use the api, or forget the correct options
to pass, there was no clear indication to the user that they were doing
so. This resulted in mockyeah still sending `200`s and just showing a
blank response.
We should be able to inform the user that they did not correctly pass
the right options, and subsequently break execution.
________________________
closes https://github.com/ryanricard/mockyeah/issues/17
=> Validate Response Object

app/index.js, app/lib/Expectation.js, app/lib/RouteManager.js, app/lib/RouteResolver.js, app/lib/RouteStore.js, package.json, test/integration/RouteExpectationTest.js
Initial implementation of adding expectation interface to all api methods. 
Example:
```js
const expectation = mockyeah
.post('/foo', { text: 'bar' })
.expect()
.header('host', 'example.com')
.params({
id: '9999'
})
.body({
foo: 'bar'
})
.once();
request
.post('/foo?id=9999')
.set('HOST', 'example.com')
.send({ foo: 'bar' })
.end(() => {
expectation.verify();
done();
});
```
=> Add mock expectation support

README.md, app/index.js, app/lib/Expectation.js, app/lib/Logger.js, app/lib/RouteManager.js, app/lib/RouteResolver.js, server/index.js, test/integration/ConfigTest.js
- Adds request journaling
- Adds ability to control mockyeah generated output, journaling, and verbosity via configuration. 
- Adds `[verbose]` output indicator
- Adds `onStart` callback to server module.
Resolves #28 
Also related to #34
=> Add output control configuration options

server/index.js
Pass server context to onStart callback and attach server root to context for easy reference.
=> Pass server context to onStart callback

app/lib/RouteResolver.js
This change lets to mock responses for the same endpoint but with different HTTP methods, 
eg.
```js
srv.delete('/rules', {status: 204});
srv.post('/rules', {status: 201}); //before this change, this line will unregister mock for delete method
```
=> RouteResolver#unregister should also test if route method matches

app/index.js, app/lib/RouteManager.js, app/lib/RouteResolver.js, package.json, test/integration/RoutePatternTest.js
This refactors `mockyeah` to use a generic route handler (`app.all('*', ...)`), and match against mocked routes within that handler. This will enable future work to support matching on things other than path, such as query parameters, headers, body, etc., similar to `nock` (here https://github.com/ryanricard/mockyeah/pull/46/files#diff-0b172c7ee81949d36b184c92f0aa5baeR24).
All existing tests pass, unmodified, and new tests were added now that we support full Express route patterns. That means we still support unregistering routes, etc.
Closes https://github.com/ryanricard/mockyeah/pull/44.
=> refactor: use generic route handler with matching

app/lib/RouteResolver.js, app/lib/routeHandler.js, test/integration/RoutePatternTest.js
This restores the ability to capture request path parameters (per Express) in custom middleware response handlers, post-refacto (https://github.com/ryanricard/mockyeah/pull/46), and closes https://github.com/ryanricard/mockyeah/issues/50.
http://expressjs.com/en/api.html#req.params
=> fix: restore request params for custom middleware

app/index.js, app/lib/RouteResolver.js, package.json
This is a simple refactoring to support future features.
With the refactoring in https://github.com/ryanricard/mockyeah/pull/46, we decided to have mockyeah defer its server listen until a route was registered, so that the generic route handler didn't run before and intercept any custom middleware registered with `mockyeah.use`. This turns out to have been a short-sighted decision for upcoming requirements to proxy, since we'd like to be able to listen even without any route registration, to support pure proxying behavior as a baseline.
This refactoring restores the behavior of listening immediately, but still supports custom middleware, by capturing a reference to any custom middleware that are registered after initial default server instantiation, but prioritizing them at request-time …
=> refactor: restore custom middleware priority with immediate listen

app/lib/CaptureRecorder.js
Refactors to fix this Node deprecation warning in the console:
```
(node:42160) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
```
This solves the issue for now and is intended to retain current behavior.
As an additional or future point of discussion, I'm not sure if it's best to continue to push these writes to the background and merely log errors asynchronously, or if we should consider bubbling the error up to Express - especially if we integrate the recording proxy feature with the generic proxying in the future (#58).
=> refactor: fix no callback warning for record write file

app/index.js, app/lib/RouteResolver.js, package.json, server/index.js, test/integration/RouteProxyTest.js, yarn.lock
Adds support for proxying any path to mockyeah URL that looks like an absolute URL to the actual backend via `http-proxy-middleware` (see below for choice rationale). Any URL can be optionally mocked as a path to prevent a trip to backend for it, while still allowing the rest through. This allows for partial mocking of real backends, so you can point to mockyeah from a real application and get mocked responses for some requests, but don't have to mock out every possible URL for all APIs used by the app to get realistic behavior. Could come in handy for local development, regression testing, demos, etc. where backend APIs can't be relied on for consistent responses to cause specific application behaviors.
Proxying behavior is disabled by default, but explicitly enabled with …
=> feat: support proxying full urls, optionally mocking

app/index.js, test/integration/ServerTest.js
This was interfering with users mounting responses on the root '/' path.
Broken since #46.
=> fix: no fake root path

app/lib/RouteResolver.js, test/integration/RoutePatternTest.js
Fixes a regression from #46 where trailing slashes were not being handled the same as before. They should be ignored when matching a mock path to a request.
=> fix: normalize path trailing slashes

app/index.js
Fixes a bug from #58 where a non-mocked, non-absolute URL was getting passed into the proxy logic and failing rather than returning 404.
=> fix: don't pass non-absolute url paths to proxy middleware

.travis.yml, docs/pages/Contributing.md
Because we no longer support it since https://github.com/ryanricard/mockyeah/pull/72.
In the future, we can transpile down, if needed.
=> chore: remove node v4 from tests & docs

app/lib/RouteResolver.js, test/integration/RoutePatternTest.js
This changes the body matching function from `_.isEqual` to `_.isMatch` to support partial matches. See the new unit test for an example. This gives us power and flexibility (which will be extended later) to match a whole class of requests with a single mock, ignoring specific fields if we choose to, such as a specific item ID in a REST API.
=> feat: support partial body matches

app/lib/CaptureRecorder.js
Tests are failing intermittently since record wasn't guaranteed to write recorded request mocks to the filesystem immediately before requests were made expecting the fixture files to exist.
This may not completely solve the issue, but it at least makes the file recording slightly more synchronous to hopefully reduce its incidence.
=> chore: make record less async for tests

docs/package.json, docs/yarn.lock
Now, from within the `docs` subfolder, you just have to run `yarn docs:publish` (after a `yarn build`) and it will publish to the `gh-pages` branch. I didn't call it `publish` because that's a native `yarn` command (`yarn publish`) and it's nice to run `yarn docs:publish` instead of `yarn run publish`. Open to suggestions for other command names.
=> chore: use gh-pages to publish gitbook

app/lib/Expectation.js, test/integration/RouteExpectationTest.js
Adds support for `expect` with custom functions to assert on behavior for `.params`, `.body`, and `.header`. In custom functions, you can either throw an exception or not, or if you return a value then the expectation will pass based on the truthiness of the return value.
I will work to add documentation after I get approval for this change.
=> feat: expect with custom functions

.eslintrc, .travis.yml, package.json, tasks/path.js, yarn.lock
This adds `husky` to enable pre-commit and pre-push hooks to run lint and test. It also updates `yarn test` to run both lint and test per Node CI conventions. You can run tests alone with `yarn test:unit`. I'm open to removing one or the other. In a follow up PR, we can move to `lint-staged` or something like it. This also adds some more exclusions to the linting, and updates some ESLint settings that might help it parse ES2015+.
=> chore: test on precommit/push hook, test script lints

app/lib/Expectation.js
We made some minor oopses in recent pulls.
=> fix: double body assertion nest, and eslint errors

app/lib/RouteResolver.js, package.json, test/integration/RoutePatternTest.js, yarn.lock
This adds feature to match against HTTP headers. Also, it adds support for using regular expressions and functions within object matches, for both existing parameters and body matches, and the new headers matches. The new regex and function matching will allow mocking requests more complexly, which will be particularly handy for something like matching based on a specific cookie using the headers matching feature this adds against the `Cookie` header. In the future, we could add a dedicated API for cookie matching functionality, but the regex and function based matching have other power too that is worthwhile.
Added unit tests for all new functionality. See those for examples.
Once approved and documentation structure is initialized, I will add.
For now, to replace/override/reset a …
=> feat: match headers, and with regex & functions

app/lib/Expectation.js, app/lib/routeHandler.js, examples/respond-with-json-function-returning-promise.js, examples/respond-with-json-function.js, examples/respond-with-json-promise.js, test/integration/ResponseDynamicTest.js
Based on https://github.com/mockyeah/mockyeah/issues/5#issuecomment-369390081, allows defining mock response data (e.g., `json`, `html`, or `text`) as a function that receives the `req` object and should return the response body data, or as a promise that resolves the data, or as a function that receives `req` and returns such a promise. This allows custom logic to change the response data based on each request.
See the added tests and examples for more details, or ask any questions.
I'll add documentation for this once we have the structure of the GitBook in place (#70).
=> feat: mock response data via function or promise

.gitignore, .travis.yml, README.md, docs/package.json, docs/yarn.lock, package.json, yarn.lock
Starts using Instanbul via `nyc` with Mocha to report on coverage on test runs. Results are pushed to Coveralls.io, which can block PRs, comment on PRs, track over time, etc.
Also updates the readme with a badge from Coveralls via https://shields.io to see coverage percentage. When #110 is merged, we'll want to add this badge there too.
=> test: add coverage tool and report to coveralls

docs/book/README.md, docs/book/SUMMARY.md, docs/package.json
Previous archive publish functionality seemed to be clobbered by additional publishes. This corrects the `docs:publish` script to support both. Pending ideas how to do this faster and more cleanly in the future. Also links to `v0.x` docs from the summary sidebar.
Relates to #70.
=> docs: link to v0.x docs and support publishing both

app/lib/RouteResolver.js, test/integration/RouteProxyTest.js
This was a bug where mocks for paths that look like absolute URLs (usually for matching with proxy), we were not checking some of the meta matches like `params`, `headers`, `body`, etc.
=> fix: support meta matches with absolute URLs

app/lib/RouteResolver.js, test/integration/RouteProxyTest.js
We were not supporting the Express path syntax like wildcards when matching paths that look like absolute URLs (for the proxy/mock use case).
Example:
```js
mockyeah.get(
'/https://api.example.com/foo(.*)',
{
fixture: 'foos.json'
}
);
```
=> feat: support path regex for absolute urls

app/lib/RouteManager.js, docs/book/API/Mock-API.md, test/integration/RoutePatternTest.js
This enables calling `mockyeah.all()` while still specifying the method but within the match object, which makes it easier to programmatically wire up mocks from a declarative definition.
In future, we could support a more generically named method like `mockyeah.mock()` or even just `mockyeah()`, where this would be especially handy.
=> feat: `all` matches method only if passed

app/lib/RouteResolver.js, test/integration/RoutePatternTest.js
Fixes #119.
Also refactors some tests for headers to use `get` instead of `post`, since that's simpler.
=> feat: match any header name casing

LICENSE.md, README.md, package.json
mockyeah is missing a license file. Looking forward to contributor feedback on the usage of the MIT license.
=> Add MIT license

lib/relativeRoot.js
`MOCKYEAH_ROOT` is useful sometimes, especially when developing through a symlink like with `npm link` or `yarn link`. But having to configure it programmatically from external code using `global` is less ideal than supporting it as an environment variable.
This also adds `path.resolve` so that we support paths relative to the current working directory for both the global and the env var.
For now, it could be used like this:
```sh
MOCKYEAH_ROOT=. node index.js
```
I'm not sure if there's a clean way to add tests for this...
=> feat: support env var MOCKYEAH_ROOT

app/lib/RouteManager.js
Routes using the object syntax for matchers were incorrectly stringifying their path on app startup, e.g.,
```
[mockyeah][16:39:30][SERVE][MOUNT][POST] [object Object]
```
This fixes the logger to always print the path of the route properly.
=> fix: log route paths correctly on app startup

.npmignore
Since we still have `mockyeah` core at the root level directory, we should exclude `packages` from the published bundle, which includes the sub-modules via `lerna` in the monorepo.
=> chore: npmignore packages

app/proxyRoute.js, app/recorder.js
Simple fix, initializes the recording set so we can safely assume it's an array later.
=> fix: initialize set for recording

packages/mockyeah/app/proxyRoute.js, packages/mockyeah/test/integration/ProxyRouteTest.js
It looks like some systems will normalize double slashes in paths, which conflicts with our notion of having the full URL to proxy in the URL path, due to the `//` in the protocol. This change will support decoding an encoded protocol string (`` is translated to `://` internally), so those systems can be supported if they pass an encoded protocol string. This should be safe against any encoded protocols later on in the URL, e.g., in its query parameters, since we only replace a leading occurrence.
=> feat: replace encoded protocol characters

packages/mockyeah/lib/prepareConfig.js, packages/mockyeah/package.json, packages/mockyeah/test/unit/prepareConfig.test.js, yarn.lock
We were trying to use `config` to apply some defaulting logic, but sometimes `config` isn't defined if you're running purely with the defaults without any config file.
=> fix: default config as empty object for default logic

.gitignore
We have to be redundant rather than allow recursive ignore, at least with `mockyeah`, since that folder name is under `packages`.
=> chore: add additional ignores for fixtures & captures

packages/mockyeah-cli/bin/mockyeah-record.js
The intent was to automatically exit the CLI prompt for record once you hit enter to stop recording.
In the future we may support one or more of the following features:
* real-time recording (update the capture file with each response)
* a separate `record-stop` command
* record on `ctrl+c` or other process kill
=> fix: exit on mockyeah record stop enter

packages/mockyeah-cli/bin/mockyeah-record.js, packages/mockyeah/app/proxyRoute.js, packages/mockyeah/app/recorder.js, packages/mockyeah/test/integration/CaptureRecordAndPlayAdminServerTest.js, packages/mockyeah/test/integration/CaptureRecordAndPlayTest.js
Adds support for a record option for headers. This will mix in the provided default headers into the match objects for recorded captures. This would support the opt-in suite-based features we have been discussing.
This is optionally provided as a `headers` object in the API, and as zero to many `--header 'Key: Value` flags in the CLI.
Added TODO comment to add tests to the CLI project, but in lieu of that for now, here's proof that at least the `collect` method works:
fixes #151
=> feat: support recording with headers

lerna.json, package.json, yarn.lock
Upgrades to the latest version of `lerna` (`3.3.1`) and runs `lerna init` to bring the config up to date per https://github.com/lerna/lerna/tree/master/commands/init#readme.
=> chore: lerna 3 upgrade

packages/mockyeah/app/lib/RouteResolver.js, packages/mockyeah/test/integration/RoutePatternTest.js
Adds support for path patching as a custom function, both as the only argument and within the object.
Also refactors to allow any query parameters in the `path` or `url` option as a string to be merged with any `query` option in the object syntax, with the latter taking precedence, so refactoring matches is easier since you won't have to convert all existing query parameters in the string into the object syntax.
fixes #176 
relates to #173
=> feat: support path matching as function & merge queries

docs/book/API/Mock-API.md
Documents behaviors added with #174 and #177 to support matching paths with regex or function. Also cleans up some old typos and adds to a few prior points, such as the `url` alias to `path`.
=> docs: add for new path matching as regex or func

lerna.json, packages/mockyeah-cli/package.json, packages/mockyeah/package.json
Corresponds with https://github.com/mockyeah/mockyeah/releases/tag/v0.18.0-alpha.1.
```console
```
```console
$ NPM_CONFIG_OTP=XXXXXX lerna publish from-git --npm-tag next
```
=> chore(release): publish v0.18.0-alpha.1

docs/book/SUMMARY.md
In #181 I forgot to update the summary (the sidebar links).
=> docs: add CLI to summary

packages/mockyeah-cli/bin/mockyeah-record.js
Fixes a bug where headers should have been defaulted to an object, not an array.
=> fix(mockyeah-cli): default headers to object

packages/mockyeah/app/proxyRoute.js
Don't record the `transfer-encoding` header since `chunked` value can cause `ParseError`s with `request` on replay.
=> fix: don't record header transfer-encoding

packages/mockyeah/app/proxyRoute.js
I flubbed the last PR (#188) deleting from the wrong headers object - probably an indication that we should modularize `proxyRoute.js` better.
=> fix: delete transfer-encoding for recording

docs/book/API/Expectation-API.md, docs/book/API/proxy.md, docs/book/API/record.md, docs/book/API/recordStop.md, docs/book/README.md, docs/book/Snapshots/Overview.md
Some fixes to documentation links between pages. Also my editor auto-formatted some of these pages and I'm to lazy right now to isolate my changes with an interactive add or continue to tiptoe around readme files with my default editor settings - let me know if that's an issue.
=> docs: fix links (and some auto-formatting)

.gitignore, docs/book/Configuration.md, packages/mockyeah-cli/bin/mockyeah-record.js, packages/mockyeah/app/lib/helpers.js, packages/mockyeah/app/proxyRoute.js, packages/mockyeah/app/recordStopper.js, packages/mockyeah/app/recorder.js, packages/mockyeah/lib/prepareConfig.js, packages/mockyeah/test/integration/CaptureRecordAndPlayAdminServerTest.js, packages/mockyeah/test/integration/CaptureRecordAndPlayTest.js, packages/mockyeah/test/unit/helpers.test.js, packages/mockyeah/test/unit/prepareConfig.test.js
This adds support for recording to put response bodies into fixture files rather than inline them into the capture files. This makes the files smaller, lighter on editors, and easier to work with and reuse for other non-capture purposes (e.g., unit tests). This can be enabled with a config value `recordToFixture === true`. We support both the `fixture` option where a fixture file path is used in the capture response options (works for `raw` as `.txt` files and JSON files), and also support the `json` option where an inline `require` call is used, enabled with config option `recordToFixturesMode === 'require'`.
~Pending documentation, which I could add in another PR.~ Added documentation.
Includes changes from #199 that were somewhat needed to deserialize JSON responses as objects in order …
=> feat: record to fixture file (path or require)

docs/book/CLI/CLI.md
Just documents the ability to pass `--help` to subcommands in the CLI. Right now we don't have all the options documented and we were not even calling out the discoverability here.
=> docs: add for subcommand help flag

packages/mockyeah/app/lib/RouteManager.js, packages/mockyeah/app/recordStopper.js
Some logs weren't printing URLs correctly for object syntax since we support both `path` and `url` as well as string URLs now. Perhaps the ideal solution would be to manipulate the different syntaxes to a normalized schema for internal use, but this will work for now.
=> fix: some logs show urls

lerna.json, packages/mockyeah-cli/package.json, packages/mockyeah/package.json
Corresponds with https://github.com/mockyeah/mockyeah/releases/tag/v0.19.0.
```console
```
```console
```
=> chore(release): publish v0.19.0

packages/mockyeah/app/lib/RouteResolver.js, packages/mockyeah/app/lib/constants.js, packages/mockyeah/app/lib/helpers.js, packages/mockyeah/app/proxyRoute.js, packages/mockyeah/test/integration/CaptureRecordAndPlayTest.js, packages/mockyeah/test/integration/RouteProxyMethodTest.js
We'll encode the URLs with URL-safe characters (`~` tildes) before compiling the path regex so colons in protocol and port aren't confused with Express parameters. This will also support allowing proxying and recording with encoded incoming URLs, which may help in some infrastructures where protocol or port character sequences like `://` and `:` in the path cause problems, e.g., if the `//` is converted to `/` by some other application or proxy layer.
=> fix: encode urls

lerna.json, packages/mockyeah-cli/package.json, packages/mockyeah/package.json
Corresponds with https://github.com/mockyeah/mockyeah/releases/tag/v0.19.1.
```console
```
```console
```
=> chore(release): publish v0.19.1

docs/book/Configuration.md, packages/mockyeah/app/recordStopper.js, packages/mockyeah/lib/prepareConfig.js, packages/mockyeah/test/formatter.js, packages/mockyeah/test/integration/CaptureRecordFormatScriptFileTest.js, packages/mockyeah/test/integration/CaptureRecordFormatScriptFunctionTest.js, packages/mockyeah/test/unit/prepareConfig.test.js
Adds feature to configure mockyeah to use a custom script to format the recorded capture JS files.
To apply custom formatting to the JS in the capture files, use `formatScript` in the config to specify a string path to a module (relative to mockyeah root near your config file) that exports a function of the signature `(js: string) : string => {}`. Or if using programatically rather than a JSON config file, you can provide a function as a value directly.
Fixes #200.
=> feat: add formatScript config for recorded captures

lerna.json, packages/mockyeah-cli/package.json, packages/mockyeah/package.json
Corresponds with https://github.com/mockyeah/mockyeah/releases/tag/v0.20.0.
```console
$ lerna version minor
```
```console
```
=> chore(release): publish v0.20.0

lerna.json, packages/mockyeah-cli/package.json, packages/mockyeah/package.json
Corresponds with https://github.com/mockyeah/mockyeah/releases/tag/v0.20.1.
```console
```
```console
```
=> chore(release): publish v0.20.1

packages/mockyeah/app/lib/RouteResolver.js, packages/mockyeah/test/integration/RouteProxyMethodTest.js
Fixes a regression with URL encoding where regex and function matches weren't being decoded.
=> fix: decode urls for regex & func match

lerna.json, packages/mockyeah-cli/package.json, packages/mockyeah/package.json
Corresponds with https://github.com/mockyeah/mockyeah/releases/tag/v0.20.2.
```console
```
```console
```
=> chore(release): publish v0.20.2

docs/book/API/Expectation-API.md, docs/book/Getting-Started.md, packages/mockyeah/app/lib/Expectation.js, packages/mockyeah/test/integration/RouteExpectationTest.js
Adds support for `expectation.verify` to optionally accept a callback to which it can pass `err` if any in traditional Node style, rather than throwing assertion errors inline. This makes integration with many testing frameworks' async support, such as `mocha` or `jest` with `done` callbacks, much easier.
Fixes #134
=> feat: expectation.verify supports callback

docs/book/API/Expectation-API.md, packages/mockyeah/app/lib/Expectation.js, packages/mockyeah/test/integration/RouteExpectationTest.js
Simple alias of `expect.params` to `.query` to align with the name of the key in the match options and in Express's `req.query`. In the future we could choose to deprecate one or the other if we wish. Adds a line to the docs.
Fixes #133
=> feat: expect.params alias to query

docs/book/API/Expectation-API.md, packages/mockyeah/app/lib/Expectation.js, packages/mockyeah/app/lib/RouteResolver.js, packages/mockyeah/eslint.config.js, packages/mockyeah/test/integration/RouteExpectationTest.js
Adds a feature for `.expect` to take an optional predicate function which is added as an assertion. It receives all the metadata it needs (path, query, headers, body, and raw request object), and can throw exceptions or return true/false to make assertions. This way, it's easier to make generic assertions, or assert on combinations of different fields.
Fixes #135.
=> feat: custom expect function with all data

packages/mockyeah/app/lib/Expectation.js, packages/mockyeah/test/integration/RouteExpectationTest.js
Add a feature to bind a callback to `.verify` (#216) with the fluent API. First it will check if the callback was past an error (e.g., a failed request), then it will execute the normal `expectation.verify` routine of running the assertions. This makes handlers a bit cleaner. Example:
Instead of:
```js
const expectation = mockyeah
.post('/foo', { text: 'bar' })
.once();
request
.post('/foo')
.end(err => {
if (err) return done(err);
expectation.verify(done);
});
```
We can now write:
```js
const expectation = mockyeah
.post('/foo', { text: 'bar' })
.once()
.done(done);
request
.post('/foo')
.end(expectation.verify);
```
Fixes #221
=> feat: add fluent way to bind verify to callback

packages/mockyeah/index.js, packages/mockyeah/package.json
This might fix the coveralls integration which couldn't find our source files ever since we switched to a monorepo with lerna.
=> chore: attempt fix coveralls paths

packages/mockyeah/app/index.js, packages/mockyeah/test/integration/RoutePatternTest.js
Adds a feature to support matching body at top-level against strings and regular expressions and functions, in addition to existing support for partial deep JSON matching.
=> feat: body string & regex mock matches

docs/book/API/Expectation-API.md, packages/mockyeah/app/lib/Expectation.js, packages/mockyeah/app/lib/RouteResolver.js, packages/mockyeah/app/lib/matches.js, packages/mockyeah/test/integration/RouteExpectationTest.js
Adds a feature to build expectations with match objects. It will deep partial match against a view into the request, and supports matching with string equality, number stringification, regular expressions, functions, etc.
```js
const expectation = mockyeah
.post("/foo", {
text: "bar"
})
.expect({
method: "post",
path: "/foo",
query: {
id: /99/,
int: 3
},
headers: value => value.host.includes("example"),
body: {
foo: "bar"
}
});
```
Fixes #219
=> feat: expect with match object

docs/book/API/Expectation-API.md, packages/mockyeah/app/lib/Expectation.js, packages/mockyeah/test/integration/RouteExpectationTest.js
Support an "after" syntax that accepts either (A) a promise or (B) a function to be passed a callback, which will wait until (A) is resolved or (B) calls callback, then will internally call `.verify`. This way, there's no need to assign `expectation` to a variable and refer to it later.
```js
mockyeah.get('/foo')
.expect({
query: { id: 10 }
})
.after(cb => request
.post('/foo?id=10')
.set('HOST', 'example.com')
.send({ foo: 'bar' })
.end(cb)
);
```
Or with promise:
```js
mockyeah.get('/foo')
.expect({
query: { id: 10 }
})
.after(fetch('/foo?id=10'));
```
Fixes #229
=> feat: expect after callback/promise

packages/mockyeah/app/lib/RouteResolver.js, packages/mockyeah/app/lib/helpers.js, packages/mockyeah/app/lib/routeHandler.js, packages/mockyeah/app/player.js, packages/mockyeah/test/integration/DynamicSuiteTest.js, packages/mockyeah/test/unit/helpers.test.js
Adds a feature to support dynamically opting into suites that are not mounted with `play` on a per-request basis using a request header `x-mockyeah-suite` matching the capture name. Unfortunately, suites will still stay in Node's `require` cache, so we can't ingest any changes to files between requests, unless we add additional features to clear the require cache on-demand, or even support a watch mode (#238).
There was some somewhat aggressive internal refactoring to support this. We'll be cleaning this up in future PRs, including possibly renaming "captures" to "suites" (#239).
This does not document yet, as we'll test it in some more real uses case before possibly tweaking then advertising.
=> feat: support dynamic suites by request header

packages/mockyeah/app/playAller.js
There was a bug with logging in `.playAll()` which had `undefined` as a message.
=> fix: undefined log for play all

packages/mockyeah/app/lib/helpers.js, packages/mockyeah/test/unit/helpers.test.js
Fixing a bug where we weren't defaulting to `get` as a method when compiling routes - especially needed for dynamic suites (#240).
=> fix: compile route default method get

packages/mockyeah/app/lib/matches.js, packages/mockyeah/test/integration/RouteExpectationTest.js
Currently, expectations weren't working with numbers against strings, since we added support for match objects in #234.
=> fix: stringify number for expectation match

packages/mockyeah/app/proxyRoute.js, packages/mockyeah/test/integration/CaptureRecordAndPlayTest.js, packages/mockyeah/test/integration/CaptureRecordFormatScriptFileTest.js, packages/mockyeah/test/integration/CaptureRecordFormatScriptFunctionTest.js
No need to record the `status` field to captures when it's `200` since we default to that anyway.
=> feat: only record status if not 200

packages/mockyeah/app/lib/routeHandler.js, packages/mockyeah/app/proxyRoute.js, packages/mockyeah/lib/prepareConfig.js, packages/mockyeah/test/integration/RouteProxyNoHeadersTest.js, packages/mockyeah/test/unit/prepareConfig.test.js
Adds headers `x-mockyeah-mocked: true` and `x-mockyeah-proxied: true` on responses so it's easier to tell what's happening, whether your mocks are matching, etc. This is on by default but can be turned off in configuration as `responseHeaders: false`.
May add documentation in a follow-up PR.
=> feat: mockyeah response headers for mocked/proxied

packages/mockyeah/app/proxyRoute.js
When we added the dynamic suite header functionality in #240, we didn't delete it from being forwarded onto the proxied service.
=> fix: don't forward x-mockyeah-suite onto proxied service

packages/mockyeah/app/lib/proxyRecord.js, packages/mockyeah/app/proxyRoute.js
The recording logic inside the proxy route file was getting a bit long, so I decide to move it to its own file.
=> refactor: move proxy record to new file

packages/mockyeah/app/lib/RouteResolver.js, packages/mockyeah/test/integration/DynamicSuiteTest.js, packages/mockyeah/test/integration/RouteProxyMethodTest.js
With the aliases feature, we forgot to decode pathnames (which can be optionally encoded) before checking. This fixes that.
=> fix: decode urls for alias check

docs/book/Configuration.md, packages/mockyeah-cli/.mockyeah.js, packages/mockyeah-cli/bin/index.js, packages/mockyeah-cli/lib/boot.js, packages/mockyeah/config.js, packages/mockyeah/package.json, packages/mockyeah/test/integration/ConfigTest.js, yarn.lock
Adds support for `.mockyeah.json` and `.mockyeah.js` config files using `cosmiconfig`.
Fixes #107.
=> feat: more config formats with cosmiconfig

packages/mockyeah/config.js, packages/mockyeah/test/integration/ConfigTest.js
With #261, we may have broken ability to run without a config. This fixes it, and adds a test so this doesn't happen again.
=> fix: restore no config behavior

packages/mockyeah/app/lib/routeHandler.js, packages/mockyeah/lib/expandPath.js, packages/mockyeah/lib/prepareConfig.js, packages/mockyeah/test/TestHelper.js, packages/mockyeah/test/integration/ConfigTest.js, packages/mockyeah/test/integration/WatchTest.js
The mockyeah root isn't working right in all scenarios. The environment variable and process global aren't flexible enough to support different tests since the `require` cache won't allow us to change them in some cases. We'll allow an optional config option `root` that overrides this when passed to `expandPath`.
=> test: correct mockyeah root

packages/mockyeah-docs/book/API/reset.md
We no longer support calling `reset` with specific routes to unmount them (since `0.15.9`), but we forgot to remove that from the docs here.
=> docs: remove unsupported reset specific routes

packages/mockyeah-cli/bin/mockyeah-record.js, packages/mockyeah/app/lib/helpers.js, packages/mockyeah/app/lib/proxyRecord.js, packages/mockyeah/app/makeAPI/makeRecord.js, packages/mockyeah/app/makeAPI/makeRecordStop.js, packages/mockyeah/lib/prepareConfig.js, packages/mockyeah/test/integration/RecordGroupsTest.js, packages/mockyeah/test/unit/prepareConfig.test.js
Fixes #252.
Also includes opt-in support to write fixtures matching specific group URL patterns to a top-level group sub-directory (at `fixtures/posts/suite-name` instead of `fixtures/suite-name`), e.g.:
```
{
"groups": {
"users": "/api/v(.*)/users",
"posts": {
pattern: "/api/v(.*)/posts",
directory: "posts" // or 'true' to use group name
}
}
}
```
Will document in a future PR.
=> feat: record groups

packages/mockyeah-cli/bin/mockyeah-record.js, packages/mockyeah-docs/book/CLI/CLI.md
We were using the optional argument syntax for some required arguments with the CLI via `commander`.
=> fix: specify required CLI arguments

packages/mockyeah-cli/bin/mockyeah-record.js, packages/mockyeah-docs/book/CLI/CLI.md, packages/mockyeah/app/lib/proxyRecord.js, packages/mockyeah/app/makeAPI/makeRecord.js, packages/mockyeah/test/integration/RecordAndPlayTest.js
Simply allows passing multiple `--only` flags to the CLI, or as an array programmatically. They are combined such that matching any one is enough to match for recording (an "or" join). Fixes #275.
=> feat: support multiple --only

packages/mockyeah/app/lib/RouteResolver.js, packages/mockyeah/app/lib/handleDynamicSuite.js, packages/mockyeah/app/lib/helpers.js, packages/mockyeah/app/lib/makeRouteHandler.js
Refactors the route handler so it doesn't need an `app` argument when defining - changes that to be passed as runtime. This is a step toward removing `app` from `compileRoute`, which will later support #282.
=> refactor: route handler

packages/mockyeah/app/lib/RouteResolver.js, packages/mockyeah/app/lib/handleDynamicSuite.js, packages/mockyeah/app/lib/helpers.js, packages/mockyeah/test/unit/helpers.test.js
Since we refactored in #286, we don't need to pass `app` to `compileRoute` anymore. This will later support #282.
=> refactor: compile route doesn't need app

packages/mockyeah/app/lib/matches.js, packages/mockyeah/app/lib/routeMatchesRequest.js, packages/mockyeah/test/unit/matches.test.js
Refactors the route request matching to use `matches` (with new short-circuit option). This decouples it from the Express request schema, in support of #282.
=> refactor: use matches for route-request matching

packages/mockyeah/app/lib/Logger.js, packages/mockyeah/package.json, packages/mockyeah/server/index.js, packages/mockyeah/test/integration/ConfigTest.js, yarn.lock
Switching from `console.log` to [`debug`](https://www.npmjs.com/package/debug) in our logger module. This library is a de facto standard for Node libraries and applications (created by TJ Holowaychuk , used in Express, etc.). It supports configuring which logs are shown via a `DEBUG` environment variable, so that users can opt in or out of various levels of logging granularity, or only monitor logs relating to particular feature(s). On a TTY terminal, it gives each type of log a different color for prettier and more readable output. It also works in the browser with `DEBUG` global (which may come in handy for #282).
For now, we still support all existing options including `output`, `verbose`, and `journal`.
We default to showing all `mockyeah*` log output if `DEBUG` is not defined. …
=> feat: use debug as logger

packages/mockyeah/app/lib/helpers.js, packages/mockyeah/app/lib/makeRouteHandler.js, packages/mockyeah/app/makeAPI/makeRecordStop.js, packages/mockyeah/lib/safeFilename.js, packages/mockyeah/test/integration/RecordBadFilenameTest.js, packages/mockyeah/test/unit/safeFilename.test.js
Strips some bad character sequences from file names, e.g., `/`, `\\`, `C:\`, `../`, etc.
=> fix: safe filenames

yarn.lock
Runs `yarn upgrade --latest --caret` to try to get all latest patched versions of dependencies.
=> chore: yarn upgrade --latest

packages/mockyeah-docs/book/Configuration.md, packages/mockyeah/app/lib/handleDynamicSuite.js, packages/mockyeah/lib/prepareConfig.js, packages/mockyeah/test/unit/prepareConfig.test.js
Lets you configure a custom header name (default `x-mockyeah-suite`) for the dynamic suite feature.
=> feat: optional custom dynamic suite header

packages/mockyeah-docs/book/Configuration.md, packages/mockyeah/app/index.js, packages/mockyeah/app/lib/handleDynamicSuite.js, packages/mockyeah/lib/prepareConfig.js, packages/mockyeah/package.json, packages/mockyeah/test/integration/DynamicSuiteTest.js, packages/mockyeah/test/unit/prepareConfig.test.js, yarn.lock
Adds a similar feature to the existing `x-mockyeah-suite` HTTP header, but now also supporting as a `mockyeahSuite` cookie, whose name, like the header, can be customized in configuration, with `suiteCookie` string. The header will take precedence over the cookie if both are provided.
Also adds `cookie-parser` middleware, which could open the door for matching by cookies as a feature on top of existing header matching in the future.
Fixes #297
=> feat: support dynamic suite as cookie

packages/mockyeah/app/lib/Logger.js
Looks like we need to restore the `always` flag for the verbose logging, broke in #296.
=> fix: verbose logging

packages/mockyeah-cli/bin/mockyeah-play.js, packages/mockyeah-cli/bin/mockyeah-record.js, packages/mockyeah-cli/package.json, yarn.lock
We had a very old version of `inquirer` which was coupling us to some older dependencies.
=> chore: upgrade inquirer

packages/mockyeah/app/lib/proxyRecord.js, packages/mockyeah/test/integration/RecordGroupsTest.js
Looks like the record group feature added in #272 had a bug where it recorded everything rather than just the items in the group. Added a negative assertion to the unit test to cover the fix.
=> fix: record groups only record matches

packages/mockyeah-cli/bin/mockyeah-record.js, packages/mockyeah-docs/book/CLI/CLI.md, packages/mockyeah/app/makeAPI/makeRecord.js, packages/mockyeah/test/integration/RecordGroupTest.js
Adds an alias `group` for `groups` since I found the pluralization sometimes confusing. Support both on the CLI as `--group` as well as programmatically with `.record({ group: { ... } })`.
Also adds support for passing `group` as a string, which can be a single group, or a comma-separated list of groups.
=> feat: add 'groups' alias 'group' & support string

packages/mockyeah-docs/book/SUMMARY.md, packages/mockyeah-docs/package.json
Deciding to no longer publish archive docs since it makes the publish process a bit complicated. Old docs should be available in the git history for those that need them.
=> chore: no longer publish archive docs

packages/mockyeah-cli/bin/index.js, packages/mockyeah-cli/bin/mockyeah-start.js, packages/mockyeah-docs/book/CLI/CLI.md, packages/mockyeah/app/makeAPI/makeUnwatch.js, packages/mockyeah/app/makeAPI/makeWatch.js
Adds a `mockyeah start` command to start up the server without playing any suites.
Also supports a `--watch` or `-w` flag to start up in watch mode, so you can ad-hoc watch even when `watch: true` is not the default in configuration.
Also adds some logging for start and stop watching.
Fixes #150.
=> feat: adds CLI start command, with --watch flag

packages/mockyeah-docs/book/Configuration.md
Looks like the `proxy` description in the configuration docs was separated from its description with some recent additions.
=> docs: correctly place config proxy description

packages/mockyeah-docs/book/API/Expectation-API.md
=> docs: fix typo 'also'

packages/mockyeah-docs/book/API/Server.md
For programmatic server use, we'll encourage importing from `mockyeah/server` directly so that we default mockyeah instance isn't started automatically, as with imports of `mockyeah` at the root level.
=> docs: import mockyeah/server

packages/mockyeah/app/lib/RouteManager.js, packages/mockyeah/app/lib/RouteResolver.js, packages/mockyeah/app/lib/handleDynamicSuite.js, packages/mockyeah/app/lib/helpers.js, packages/mockyeah/app/lib/logMatchError.js, packages/mockyeah/app/lib/routeMatchesRequest.js, packages/mockyeah/app/makeAPI/makePlay.js
Adds verbose logs for any match errors for incoming requests. Includes suite name, index of mock within suite, and the error message including key path.
=> feat: log request match errors (verbosely)

packages/mockyeah/server/index.js
Seeing errors in tests when calling `.close()` in `after()` but the server has somehow already stopped running. Adding a check to suppress the `ERR_SERVER_NOT_RUNNING` error.
=> fix: no error on close when not running

packages/mockyeah/server/index.js
To support handling the "server not running" error when calling `close` (#345) for Node less than 8, where `error.code` does not exist, we need to also check the error message.
=> fix: detect server not running errors in Node 6

packages/mockyeah/app/makeAPI/makeWatch.js, packages/mockyeah/test/integration/WatchTest.js
Adds an optional callback to `.watch()` and returns a Promise. Uses `chokidar`'s `ready` event.
=> feat: watch callback and promise

packages/mockyeah/test/TestHelper.js
Use the new `close` promise support to make sure tests `after` waits for servers to close.
=> test: after all use close promises

packages/mockyeah/app/lib/RouteResolver.js
Make sure `reset` really resets all routes, even if we have bugs in `isRouteMatch`.
=> refactor: unregister all routes

packages/mockyeah/app/lib/RouteResolver.js, packages/mockyeah/test/integration/MissedTest.js, packages/mockyeah/test/integration/RouteProxyTest.js
Adds a `x-mockyeah-missed: true` header when no mock matches, whether or not we are proxying (so it may co-occur with `x-mockyeah-proxied: true` header.
=> feat: x-mockyeah-missed header

packages/mockyeah-docs/book/API/close.md, packages/mockyeah-docs/book/API/shutdown.md, packages/mockyeah/server/index.js, packages/mockyeah/test/integration/WatchTest.js
We don't really need a separate `.shutdown()` command to `.close()` and `.unwatch()`. I'd added this not too long ago but am deciding to remove it for simplicity. Technically a breaking change, but probably few using it yet since it's not documented, so not a huge deal.
=> feat: close() unwatches, remove shutdown()

packages/mockyeah-cli/bin/index.js
This inadvertent double call to `program.parse` was breaking `-V, --version`, and probably causing other problems.
Fixes #323.
=> fix(cli): remove extra program parse

packages/mockyeah-cli/bin/index.js, packages/mockyeah-cli/bin/mockyeah.js
This allows us to use `node bin/mockyeah start` in development, whereas before it would complain that `index-start` does not exist, and fail. Moves logic from `bin/index.js` to `bin/mockyeah.js`, which `bin/index.js` now `require`s. Also adds ` .name('mockyeah')` to the commander setup for console messages.
=> refactor(cli): move bin/index to bin/mockyeah

packages/mockyeah-cli/bin/mockyeah-list.js, packages/mockyeah-cli/bin/mockyeah.js
For CLI, renames `ls` to `list` for better usability, but adds an alias `ls` to it to retain that option. Also adds an alias `play-all` to `playAll` in case people try to use the kebab-case form usually seen in subcommand apps like this.
=> feat(cli): aliases for list and play-all

packages/mockyeah/test/integration/RecordAndPlayAdminServerTest.js, packages/mockyeah/test/integration/RecordAndPlayTest.js, packages/mockyeah/test/integration/RecordBadFilenameTest.js, packages/mockyeah/test/integration/RecordFormatScriptFileTest.js, packages/mockyeah/test/integration/RecordFormatScriptFunctionTest.js, packages/mockyeah/test/integration/RecordGroupTest.js, packages/mockyeah/test/integration/RecordGroupsTest.js, packages/mockyeah/test/integration/RouteResetTest.js, packages/mockyeah/test/integration/WatchTest.js
In tests, we should always use the promise or callback support of `.close()` to be sure async handles are captured.
=> test: use close() async properly

packages/mockyeah/app/lib/handleDynamicSuite.js, packages/mockyeah/test/integration/DynamicSuiteTest.js
You can now pass multiple, comma-separated suite names in the `x-mockyeah-suite` header or cookie for dynamic suite opt-in per request.
Fixes #326.
=> feat: multiple dynamic suites

packages/mockyeah-cli/README.md
We had an old GitHub link in the README for the CLI.
=> docs(cli): update github link in README

packages/mockyeah-docs/book/Testing.md
Fix typo in the `npm` install commands under `Testing` section.
=> docs: fix testing install commands

packages/mockyeah-cli/README.md, packages/mockyeah-test-jest/README.md, packages/mockyeah-test-mocha/README.md, packages/mockyeah/README.md
Looks like the URL for the logo images in the sub-repo READMEs was wrong.
=> docs: fix images in sub-repo readmes again

packages/mockyeah/server/index.js, packages/mockyeah/test/integration/LazyStartTest.js
Looks like lazy start wasn't attaching a `.server` reference to the instance, so we couldn't get the `url` from unit tests in `mockyeah-test-jest`. Refactoring this so the property can be added to the instance dynamically.
=> fix: refactor server instance for lazy start reference

packages/mockyeah/test/integration/ResponseContentTypeTest.js, packages/mockyeah/test/integration/ResponseHeadersTest.js
Tests are flaking sometimes looking for `text/xml` but getting `application/xml`. Not sure why right now, but both behaviors seem acceptable, so we'll update the tests to only assert `/xml`.
=> test: assert /xml not text/xml

packages/mockyeah/test/integration/RouteExpectationTest.js
Change the expect header tests to use a custom header instead of `host`, and removes a redundant test.
=> test: expect header other than host

packages/match-deep/src/index.ts, packages/mockyeah/test/integration/RouteExpectationTest.js
We should period-separate multiple error messages from `match-deep`.
=> fix: match-deep errors period-separated

packages/mockyeah-cli/package.json
Looks like with #436 we missed one dependency update.
=> chore(cli): depend on @mockyeah/server

.travis.yml
We should run Travis on more than just the `master` branch, so it also runs on the `v0` branch.
=> build: travis not only on master (v0)

packages/mockyeah/app/lib/helpers.js, packages/mockyeah/test/unit/helpers.test.js
Updates `handleContentType` to handle cases where `body` is already an object (may have been parsed already).
This is only needed in the `v0` branch because in `master` with `v1` we always do a `fetch().text()`.
=> fix: handleContentType with body as object

packages/mockyeah-cli/lib/boot.js
When trying `npx @mockyeah/cli` for the `1.0.0-alpha.0` version, I was getting this:
```
Local mockyeah not found in /Users/me/code/mockyeah/packages/mockyeah-cli
Try running: npm install @mockyeah/server --save-dev
```
This attempts to fix that by having Liftoff look for the `@mockyeah/server` module instead.
=> fix(cli): liftoff with new @mockyeah/server module name

packages/mockyeah-cli/lib/__tests__/checkVersionMatch.test.js, packages/mockyeah-cli/lib/checkVersionMatch.js, packages/mockyeah-cli/package.json
Updating the CLI version mismatch checking to use semantic versioning instead of requiring exact match.
=> feat(cli): version mismatch check uses semver

.travis.yml, package.json, packages/match-deep/package.json, packages/mockyeah-cli/package.json, packages/mockyeah-docs/package.json, packages/mockyeah-fetch/package.json, packages/mockyeah/package.json
The docs build is failing right now locally for some reason, so I can't run `npm run build` before publishing. There's no need to run the docs build on CI anyway for now, so decoupling build into `build` and `build:ci` versions. I'll use `build:ci` for now to build before publishing locally.
=> build: switch to npm and don't build docs on CI

packages/mockyeah-fetch/package-lock.json, packages/mockyeah-fetch/package.json, packages/mockyeah-fetch/src/__tests__/index.test.ts, packages/mockyeah-fetch/src/index.ts, packages/mockyeah-fetch/src/types.ts
Adds support for `req.cookies` passed to dynamic mock response functions.
Fixes #468.
=> feat(fetch): cookies for dynamic responses

packages/match-deep/.gitignore, packages/mockyeah-fetch/.gitignore
Simply ignore `*.js` files under `src` for the packages using TypeScript.
=> chore(fetch,match-deep): gitignore src js

packages/mockyeah-docs/package-lock.json, packages/mockyeah-docs/package.json
On trying to start the `@mockyeah/docs` Gatsby locally for development, I was getting this error - I think due to old version of Gatsby CLI installed globally and older versions of React:
```
The above error occurred in the <StoreStateProvider> component:
in StoreStateProvider
in App
React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
```
Inlining dependency on latest Gatsby CLI and upgrading React seemed to fix.
=> docs: update gatsby & react versions

packages/mockyeah-fetch/src/index.ts, packages/mockyeah-fetch/src/types.ts, packages/mockyeah/app/index.js, packages/mockyeah/test/integration/ResponseValidationTest.js
Enhances logging for `@mockyeah/fetch` by including optional instance name (defaults to `default`) as a prefix in all log and error messages.
Also adds the match miss message to those logs.
Also adds logging for when a mock is registered (and changes the debug key for hits).
=> feat(fetch): log instance name and on mocking

packages/mockyeah-docs/src/menus.js, packages/mockyeah-docs/src/pages/Recipes-and-Examples.md
Originally I set out to fix the URL for "Recipes & Examples" at https://mockyeah.js.org/ but you already corrected it. I added a page reviewing what we were discussing in [this issue](https://github.com/mockyeah/mockyeah/issues/484).
`npm start` from the project root.
---
Do you want this? Is there anything else to add?
=> docs: recipes and examples page: examples, deps, and tests links

.travis.yml, package.json, packages/mockyeah-docs/src/pages/Contributing.md
It's possible to run `lerna` right after the contributor does `npm install`. This PR adds that script into `package.json`. But, lets say we have a user that does `npm install --ignore-scripts` but they still want to help. It's no problem! On the Contributing.md docs page it will walk them through.
Bonus: docs site url
```sh
git clone -b contributing-lerna-bootstrap https://github.com/youreadforme/mockyeah.git
cd mockyeah
npm install
```
↑ We'll notice right there it also runs lerna. I ran the unit tests locally and they didn't pass but I don't think it's related to this PR. 🤷‍♂
=> build: lerna package.json postinstall and contributing docs

packages/mockyeah-fetch/src/index.ts, packages/mockyeah/app/lib/helpers.js, packages/mockyeah/test/integration/RecordFormatScriptFileTest.js, packages/mockyeah/test/integration/RecordFormatScriptFunctionTest.js, packages/mockyeah/test/integration/ResponseValidationTest.js
Don't require specifying any response data - defaults to empty string.
=> feat: allow empty response

packages/mockyeah/package.json, yarn.lock
Seems there are a couple `High` vulns introduced by mockyeah's dependencies
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ set-value                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.0.1 <3.0.0 || >=3.0.1                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ mockyeah                                                     │
├───────────────┼─────────────────────────────────────────────────────── …
```
=> chore: address vulns by version bumping chokidar

packages/mockyeah-test-jest/index.js, packages/mockyeah-test-mocha/index.js
We don't want to use the `WebSocket` functionality in the test packages.
=> fix: test packages no websocket

packages/mockyeah-fetch/src/Expectation.ts, packages/mockyeah-fetch/src/index.ts, packages/mockyeah-fetch/src/types.ts
Moving the functions on the `@mockyeah/fetch` `Mockyeah` instance to class methods so they're including in the exported types. Also clean up some other types along the way.
=> refactor: fetch methods on class

packages/mockyeah-fetch/src/__tests__/normalize.test.ts, packages/mockyeah-fetch/src/normalize.ts
Fixes `match.$meta.originalNormal` to include query parsed from URL string and other bits we missed. This was causes routes with same paths but different queries to clobber each other on mounting.
=> fix(fetch): full meta original normal

packages/mockyeah-fetch/src/index.ts, packages/mockyeah-fetch/src/parseBody.ts
Looks like some other libraries can't handle `undefined` string. Perhaps it should've been `null`. To be safe, we'll just always return an empty string in these cases for now.
=> fix(fetch): body always empty string

packages/mockyeah-fetch/src/Expectation.ts
In some cases, expectations were failing due to `{}` not equaling `undefined`, so we'll always default to empty objects when comparing params.
=> fix(fetch): expect params default object

packages/mockyeah-fetch/src/__tests__/index.test.ts, packages/mockyeah-fetch/src/index.ts, packages/mockyeah-fetch/src/types.ts
Fix up types to allow optional response body, response body fields, and fetch init object. Also add a test proving no response options are needed.
=> fix(fetch): optional fetch init & response options

packages/mockyeah-fetch/src/__tests__/index.test.ts, packages/mockyeah-fetch/src/index.ts, packages/mockyeah-fetch/src/isMockEqual.ts, packages/mockyeah-fetch/src/normalize.ts, packages/mockyeah-fetch/src/types.ts
Adds support to `@mockyeah/fetch` for mocks to match against a `cookies` object, which we pull from `headers` on the request if available, else from `document.cookies` in `window`ed environment like the browser.
For example, this would match any request with the cookie `say` with value `hi`:
```ts
mockyeah.get({
cookies: {
say: 'hi'
}
}, { text 'hi!' })
```
Fixes #473.
=> feat(fetch): match cookies

packages/mockyeah-fetch/src/index.ts, packages/mockyeah-fetch/src/isMockEqual.ts, packages/mockyeah-fetch/src/types.ts
Adds a config option to specify a dynamic mock suite resolver. Which suite(s) to resolve comes from either the `dynamicMockSuite` option on `mockyeah.fetch`, or from the cookie specified in `config.suiteCookie` (default `mockyeahSuite`).
Fixes #482.
=> feat(fetch): dynamic mock suite resolver

packages/mockyeah-fetch/src/index.ts
Only adds suite header to fallback fetches when prepending server URL. This was originally written to support dynamic mocks with server integration. We may remove the server integration feature someday.
=> fix(fetch): only add suite header when prepending server url

packages/mockyeah-docs/package.json
This placeholder test fails so it's useless for now.
=> test(docs): remove placeholder test script

packages/mockyeah-fetch/src/index.ts
The fetch-blocking websocket connection attempt shouldn't retry.
Also enhances some error handling for websocket.
=> fix(fetch): no retries on blocking fetch websocket

packages/mockyeah/server/withAdminServer.js
Send record event after connection in case we don't connect before the event was sent.
=> fix(server): send record after connect

packages/mockyeah-fetch/src/index.ts, packages/mockyeah-fetch/src/types.ts
We'll remove the `@mockyeah/fetch` websocket auto-connect on instantiation and auto infinite retry since we have the fetch-blocking connect attempts anyway which is simpler and less noisy.
BREAKING CHANGE
=> feat!(fetch): remove websocket auto-connect & retry

packages/mockyeah-fetch/src/index.ts, packages/mockyeah-fetch/src/types.ts
Should've removed this now unused option with #520.
=> fix(fetch): remove websocket interval option

packages/mockyeah-fetch/src/index.ts
In case the websocket server closes, we should reset the recording flag back to false.
=> fix(fetch): stop recording on websocket close

package.json
Formats `lerna.json` with `prettier` after `lerna version` using the top-level `postversion` hook (hoping this works).
=> chore: prettify lerna.json on postversion

packages/mockyeah-fetch/src/index.ts
We should've been using `bootOptions.fetch` instead of global `fetch` in the fallback method.
=> fix(fetch): fallback uses options fetch not global

packages/mockyeah-docs/src/pages/API/Mock-API.md, packages/mockyeah-fetch/src/respond.ts
Not sure if this is a bug fix or a new feature, but if we get `type` in response options, we try to map it to a MIME type using `mime`'s `getType`, otherwise we send no type. We can instead fallback to the raw `type` passed to support unknown or custom MIME types.
=> fix(fetch): fallback to type if no mime type mapping

packages/mockyeah-docs/src/pages/API/Mock-API.md, packages/mockyeah-fetch/src/__tests__/index.test.ts, packages/mockyeah-fetch/src/handleEmptyBody.ts, packages/mockyeah-fetch/src/headersToObject.ts, packages/mockyeah-fetch/src/index.ts, packages/mockyeah-fetch/src/parseResponseBody.ts, packages/mockyeah-fetch/src/respond.ts, packages/mockyeah-fetch/src/types.ts
Response option functions like  functions like `json`, `text`, `status`, `headers`, etc., can now be defined with a 2nd `res` argument after existing `req` argument. Any such response option will cause Mockyeah to actually make a real fetch call to that URL, and then give your function the response data as `res` (with `status`, `headers`, and `body` fields) which you can then manipulate or derive a mock response.
Fixes #403.
Relates to #441.
=> feat(fetch): intercept response

packages/mockyeah-docs/gatsby-browser.js, packages/mockyeah-docs/package-lock.json, packages/mockyeah-docs/package.json, packages/mockyeah-docs/src/components/Alert.js, packages/mockyeah-docs/src/components/header.js, packages/mockyeah-docs/src/components/layout.css
Adds an alert to the top of the new `1.x` docs site pointing users to the legacy docs for `0.x`.
=> feat(docs): add alert for mockyeah 0.x docs

packages/mockyeah-docs/CNAME
We don't need CNAME anymore since we're using Netlify.
=> chore(docs): remove CNAME (v0)

packages/mockyeah/test/integration/RecordNothingTest.js
Fix the server record nothing test by not using an absolute URL to make the proxy requests since it's failing with the new mockyeah.js.org site with this error:
```
Error: Parse Error: Content-Length can't be present with chunked encoding
at Socket.socketOnData (_http_client.js:470:22)
at addChunk (_stream_readable.js:341:12)
at readableAddChunk (_stream_readable.js:316:11)
at Socket.Readable.push (_stream_readable.js:250:10)
at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```
=> test(server): fix record nothing test without proxying

packages/mockyeah-docs/src/components/header.js
Update mockyeah `0.x` docs link to use a trailing slash since for whatever reason with that it isn't redirecting to `mockyeah.js.org` on Netlify like it is without the trailing slash. Maybe this is just a DNS TTL thing but for now this should work.
=> fix(docs): update mockyeah 0.x docs link

packages/mockyeah-docs/CNAME
We don't need CNAME anymore since we're using Netlify.
=> chore(docs): remove CNAME

packages/mockyeah-docs/src/pages/Integration.md
Some minor updates to integration docs for `@mockyeah/fetch`. More to come including a possible major rewrite where `@mockyeah/fetch` is the primary tool advertised and `@mockyeah/server` is moved to a subsection.
=> docs: update fetch integration

packages/mockyeah-fetch/src/index.ts, packages/mockyeah-fetch/src/types.ts
Don't assume a `default` export in mock suites loaded, but check for it first for compatibility with both TS/ES Modules transpiled code and also with traditional CommonJS/Node `module.exports` code.
=> fix(fetch): mock suite resolver not assume default

packages/mockyeah-fetch/src/__tests__/normalize.test.ts, packages/mockyeah-fetch/src/normalize.ts, packages/mockyeah-fetch/src/types.ts
Updates `@mockyeah/fetch` `normalize` method to include a serialized version of the normalized original match object. This improves the ability to serialize mocks over JSON. For now we only serialize regular expressions, since functions can't really be easily serialized (at least not ones which might access higher scoped variables - perhaps in future we could try to detect those that only access internal scope and serialize those somehow - maybe with something like [`serialize-javascript`](https://www.npmjs.com/package/serialize-javascript)).
=> feat(fetch): normalize adds meta original serialized

.travis.yml
Hopefully lets Travis report failure faster after CI fails for any Node version.
=> build(travis): add jobs.fast_finish

packages/mockyeah-fetch-demo/package.json
Making `@mockyeah/tools` an optional dependency for `@mockyeah/fetch-demo` so it can skip installing that private package on Netlify builds.
=> chore(fetch-demo): optional tools dep for netlify

packages/mockyeah-fetch-demo/README.md
`@mockyeah/fetch-demo` was missing a README - adding one with a link to the its Netlify site. https://mockyeah-fetch-demo.netlify.com/
=> docs: add README for @mockyeah/fetch-demo

packages/mockyeah-fetch-demo/webpack.config.babel.js, packages/mockyeah-web-extension/package.json, packages/mockyeah-web-extension/webpack.config.ts
So `.js` files are getting compiled alongside `.ts` files during local development which causes Webpack to pick up the wrong files.
=> build: only ts files for web ext & fetch demo

packages/mockyeah-web-extension/package.json
Build scripts for the web extension will default to production now.
=> build(webext): update scripts with default production

packages/mockyeah-web-extension/README.md
The README link to the `.crx` file should've had `?raw=true` to trigger a download.
=> docs(webext): crx raw link

packages/match-deep/package-lock.json, packages/mockyeah-fetch/package-lock.json
Fixes a moderate severity vulnerability in `serialize-javascript` `< 2.1.1`.
=> chore: npm audit fix

packages/mockyeah-fetch/src/respond.ts, packages/mockyeah-web-extension/README.md
The latency function should receive the `res` argument as well. Latency is added to the top of the actual underlying request (for now). Relates to #424
=> feat(fetch): latency function gets response

packages/mockyeah-docs/src/pages/API/Mock-API.md, packages/mockyeah-fetch/src/Expectation.ts, packages/mockyeah-fetch/src/normalize.ts, packages/mockyeah/app/makeAPI/makePlay.js
Mocks for all methods or unspecified methods were defaulting to `get` and missing.
=> fix(cli): mock all method

packages/mockyeah-fetch/src/__tests__/index.test.ts, packages/mockyeah-fetch/src/index.ts
Looks like in the request handlers we weren't including optional port and host.
=> fix(fetch): request for handler gets port & host

packages/mockyeah-fetch/src/__tests__/index.test.ts, packages/mockyeah-fetch/src/parseResponseBody.ts, packages/mockyeah/app/index.js
Use `body-parser`'s `extended: true` mode and switch to `qs` from `querystring` for form data matching.
=> feat: extended form data matching

package.json, packages/mockyeah-fetch-demo/package.json, packages/mockyeah-fetch-demo/webpack.config.babel.js
For `@mockyeah/fetch-demo`, I'm adding webpack resolve path `'..'` so it can find packages for monorepo build on Netlify which doesn't seem to allow `lerna link`'s writes to `node_modules`.
Also adding `build:ci` script to `@mockyeah/fetch-demo` so Netlify build command doesn't have to individually build `match-deep` and `@mockyeah/fetch` and this, but just one `build:ci` command.
Also scoping the top-level `postinstall` run of `lerna bootstrap` to not run on Netlify.
=> build(fetch-demo): resolve packages and build:ci

.github/workflows/automerge.yml
It seems that the `!work in progress` may not be working, so switching automerge to opt-in.
=> chore(workflows): require automerge label

package.json
Netlify's `node_modules` cache keeps around symlinks to monorepo packages whose targets don't exist on rebuilds causing npm checkPermissions WARN errors. We'll remove these if they exist in `preinstall` so that things proceed as normal.
=> chore: preinstall rm node_modules symlinks for netlify

packages/mockyeah-fetch/src/Expectation.ts, packages/mockyeah-fetch/src/__tests__/index.test.ts, packages/mockyeah-fetch/src/types.ts, packages/mockyeah-web-extension/package-lock.json
Enhances some types for the object valued properties of matches like `query`, `headers`, and `cookies`, and those for expectations like `query` and `params`. Mostly just makes sure the function forms receive primitive valued versions of the objects without and nested function or regex matchers.
=> fix(fetch): object match types

packages/match-deep/src/index.ts, packages/mockyeah-fetch/src/normalize.ts, packages/mockyeah-fetch/src/types.ts, packages/mockyeah/test/integration/RouteExpectationTest.js
Now we'll provide a stringified version of match functions for use in logging of match failures for the `url` if it was originally derived from a string or regex.
=> feat: match log function as string

packages/mockyeah-fetch/webpack.config.babel.js
Should've published the workbox script for direct consumption by custom service workers as needed per recent docs additions.
=> fix(fetch): publish workbox script

packages/mockyeah-fetch/src/workbox.ts
Removing the useless `async` function in the `workbox` script since that causes it to get the regenerator runtime in its output.
=> refactor(fetch): no async in workbox

packages/mockyeah-fetch/webpack.config.babel.js
Need to publish `workbox` script as a library so it exposes its exports.
=> fix(fetch): publish workbox as library

packages/mockyeah-cli/bin/mockyeah.js
Don't call `boot` in the root `bin` script since it's called by each command file individually as well.
=> fix(cli): no call boot in root bin

packages/mockyeah-cli/lib/boot.js
Restore the default debug logs for the mockyeah CLI.
=> fix(cli): default debug

packages/match-deep/package.json, packages/mockyeah-cli/README.md, packages/mockyeah-cli/package.json, packages/mockyeah-docs/src/pages/Compare/index.mdx, packages/mockyeah-docs/src/pages/Packages/mockyeah-fetch/index.mdx, packages/mockyeah-docs/src/pages/Packages/mockyeah-server/index.mdx, packages/mockyeah-docs/src/pages/Packages/mockyeah-test-jest/index.mdx, packages/mockyeah-docs/src/pages/Packages/mockyeah-test-mocha/index.mdx, packages/mockyeah-docs/src/pages/WebExtension/index.mdx, packages/mockyeah-docs/src/pages/index.mdx, packages/mockyeah-fetch/README.md, packages/mockyeah-fetch/package.json, packages/mockyeah-test-jest/README.md, packages/mockyeah-test-jest/package.json, packages/mockyeah-test-mocha/README.md, packages/mockyeah-test-mocha/package.json, packages/mockyeah-test-server-jest/README.md, packages/mockyeah-test-server-jest/package.json, packages/mockyeah-test-server-mocha/README.md, packages/mockyeah-test-server-mocha/package.json, packages/mockyeah-web-extension/README.md, packages/mockyeah/README.md, packages/mockyeah/package.json
Updating `package.json` adding `directory` to `repository` for each monorepo package, adding `homepage` to link to new docs site, update README URLs to new docs site. Also cross-link some package and getting started pages in the docs, and move the homepage compare blurb to compare page. Also fixing the web extension install instructions since it requires loading unpacked now.
=> chore: package and docs updates

packages/mockyeah-fetch/src/index.ts
Dynamic matches are not always cookie-based - sometimes they are passed as a `dynamicMockSuite` argument to `fetch`. In those cases, we should not augment the match with the cookie value.
=> fix: no dynamic match cookie

packages/mockyeah-fetch/src/index.ts, packages/mockyeah-fetch/src/respond.ts
On request match, we'll log the parsed response body and headers too, since the `Response` instance itself can obscure those behind the `Body` `ReadableStream` and `Headers` classes respectively.
Also, we'll try to attach the `url` to the `Response` object so it behaves more uniformly to a normal `Response`, even though the constructor doesn't seem to allow this.
=> feat: enhance match logging, add response url

packages/mockyeah-fetch/src/respond.ts
We now will log parsed body as `json` for a `fixture` or `filePath` mock with type of JSON (based on explicit passing `type: 'json'` or by inferring `.json` extension from file name).
Logs look like this now:
```
mockyeah:fetch:hit [mockyeah] @mockyeah/fetch matched mock for /service/exists {
request: {
url: '/service/exists',
path: '/service/exists',
query: undefined,
method: 'get',
headers: {
'accept-encoding': 'gzip, deflate',
'user-agent': 'node-superagent/3.8.3',
connection: 'close'
},
body: undefined,
cookies: undefined
},
mock: [
{
url: [Function],
method: 'get',
headers: undefined,
'$meta': [Object]
},
{ name: undefined, fixture: 'some-data.json' }
],
response: Body {
url: '/service/exists',
status: 200,
statusText: 'OK',
headers: Headers { _headers: [Object] },
ok: true,
body: …
```
=> feat: parse json from fixture/file for logs
