mockyeah/mockyeah

- index.js
I know this was express gen, but we can use template strings now, so I updated it.
> Use Template Strings for Server and Port

- README.md
This should help with allowing users to understand the ability for them to update
default configurations and adjust them accordingly.
> Document .mockyeah configuration file

- app/lib/RouteResolver.js
- test/integration/RouteRegisterTest.js
Response to issue https://github.com/ryanricard/mockyeah/issues/20 and pr https://github.com/ryanricard/mockyeah/pull/21.
> Unregister existing matching routes

- test/integration/ResponseContentTypeTest.js
- test/integration/ResponseHeadersTest.js
This must have started failing with a new verison of Node or express?
> test: update to text/xml

- .travis.yml
Execution automation against multiple node versions.
> Modify Travis CI config

- app/index.js
- app/lib/RouteResolver.js
Adds comments requested in PR reviews https://github.com/ryanricard/mockyeah/pull/57#discussion_r159106617 and https://github.com/ryanricard/mockyeah/pull/55#discussion_r159106181.
> chore: add comments per previous PR reviews

- app/lib/RouteManager.js
- examples/respond-to-ALL-REST-methods.js
- examples/respond-to-PATCH-REST-method.js
- test/integration/RouteRegisterTest.js
Same approach as put — but we need "patch" for our current project.
> Support for "patch"!

- gulpfile.js
- test/integration/ConfigTest.js
- test/integration/RouteExpectationTest.js
- test/integration/RouteRegisterTest.js
- test/integration/RouteResetTest.js
> style: fix eslint warnings

- test/integration/ConfigTest.js
> style: no extra space in a test case name

- app/lib/RouteResolver.js
- docs/book/API/proxy.md
- test/integration/RouteProxyTest.js
> feat: define mocks for proxy without leading slash

- app/index.js
- docs/book/API/proxy.md
- docs/book/Configuration.md
- test/integration/RouteProxyMethodTest.js
- test/integration/RouteProxyTest.js
> feat: add proxy option to configuration

- app/lib/RouteResolver.js
- test/integration/RoutePatternTest.js
> feat: support alias `url` of `path`

- packages/mockyeah/app/lib/RouteResolver.js
- packages/mockyeah/test/integration/RoutePatternTest.js
> fix: stringify number params before match

- docs/book/API/Mock-API.md
- packages/mockyeah/app/lib/RouteResolver.js
- packages/mockyeah/test/integration/RoutePatternTest.js
If approved, I can add or follow up with documentation.
closes #173
> feat: support regex matching on paths

- packages/mockyeah/test/integration/RouteProxyTest.js
> chore: remove an extraneous console.log

- packages/mockyeah/eslint.config.js
- packages/mockyeah/test/.eslintrc
There are no new errors or warnings with this change - only one existing which is fixed by #166.
> style: test eslint config extends default

- packages/mockyeah-cli/bin/mockyeah-playAll.js
- packages/mockyeah/app/index.js
- packages/mockyeah/app/playAller.js
- packages/mockyeah/app/proxyRoute.js
- packages/mockyeah/server/admin.js
- packages/mockyeah/server/index.js
- packages/mockyeah/test/integration/CaptureRecordAndPlayAdminServerTest.js
- packages/mockyeah/test/integration/CaptureRecordAndPlayTest.js
> feat: play all API and CLI

- packages/mockyeah/app/lib/Expectation.js
- packages/mockyeah/app/lib/RouteResolver.js
- packages/mockyeah/app/lib/matches.js
- packages/mockyeah/test/integration/RouteExpectationTest.js
- packages/mockyeah/test/integration/RoutePatternTest.js
Aggregates multiple match errors and provides rich error messages for all match failures including full key paths for deep partial match failures and serializing the source/value of each failure for comparison.
Closes #233.
> feat: match errors aggregated

- packages/mockyeah/server/index.js
When we introduced the admin server a while back, we never included it in the `.close` method we expose to control shutdown. This fixes that.
> fix: close admin server

- packages/mockyeah/app/lib/RouteResolver.js
- packages/mockyeah/app/lib/routeMatchesRequest.js
Simple refactor, working towards supporting #282 and #155.
> refactor: new file for route match request logic

- packages/mockyeah/app/lib/RouteResolver.js
- packages/mockyeah/app/lib/handleDynamicSuite.js
Simple refactor for `handleDynamicSuite`, moving to a new file to increase modularity.
> refactor: new file for handle dynamic suite

- packages/mockyeah-cli/README.md
- packages/mockyeah/README.md
Trying to fix the images in the readmes as they're published to npm.
> docs: fix images in sub-repo readmes

- yarn.lock
Ran `yarn upgrade-interactive` to get latest patched versions of dependencies.
> chore: yarn upgrade-interactive

- packages/mockyeah-docs/book/API/Expectation-API.md
- packages/mockyeah-docs/book/API/Match-Values.md
- packages/mockyeah-docs/book/API/Mock-API.md
- packages/mockyeah-docs/book/API/Server.md
- packages/mockyeah-docs/book/Configuration.md
- packages/mockyeah-docs/book/SUMMARY.md
- packages/mockyeah-docs/book/Suites/Dynamic.md
Updates docs for some recent features such as dynamic suites (#240, #297), record groups (#272), aliases (#255), match objects for expectations (#228, #234), etc.
> docs: update for recent features

- packages/mockyeah-cli/bin/mockyeah-record.js
- packages/mockyeah-docs/book/API/recordStop.md
- packages/mockyeah/app/lib/helpers.js
- packages/mockyeah/app/makeAPI/makeRecordStop.js
- packages/mockyeah/package.json
- packages/mockyeah/server/admin.js
- packages/mockyeah/test/integration/RecordAndPlayAdminServerTest.js
- yarn.lock
> feat: on record stop, don't write if say no

- lerna.json
- packages/mockyeah-cli/package.json
- packages/mockyeah/package.json
Corresponds with https://github.com/mockyeah/mockyeah/releases/tag/v0.22.1.
```console
$ lerna version 0.22.1
```
> chore(release): publish v0.22.1

- packages/mockyeah-docs/book/API/Mock-API.md
> docs: add for wildcards

- packages/mockyeah-docs/book/API/Mock-API.md
- packages/mockyeah/app/lib/makeRouteHandler.js
- packages/mockyeah/test/integration/ResponseValidationTest.js
- packages/mockyeah/test/integration/RoutePatternTest.js
> feat: mount text response shorthand

- packages/mockyeah/app/makeAPI/makeRecordStop.js
- packages/mockyeah/test/integration/RecordNothingTest.js
> feat: no record files if no matches

- lerna.json
Adding new packages `mockyeah-test-jest` and `mockyeah-test-mocha` to `lerna.json`.
> chore: add new packages to lerna.json

- lerna.json
- packages/mockyeah-cli/package.json
- packages/mockyeah-test-jest/package.json
- packages/mockyeah-test-mocha/package.json
- packages/mockyeah/package.json
Corresponds with https://github.com/mockyeah/mockyeah/releases/tag/v0.23.1.
```console
$ lerna version 0.23.1
```
> chore(release): publish v0.23.1

- lerna.json
- packages/mockyeah-cli/package.json
- packages/mockyeah-test-jest/package.json
- packages/mockyeah-test-mocha/package.json
- packages/mockyeah/package.json
Corresponds with https://github.com/mockyeah/mockyeah/releases/tag/v0.23.2.
```console
$ lerna version 0.23.2
```
> chore(release): publish v0.23.2

- lerna.json
- packages/mockyeah-cli/package.json
- packages/mockyeah-test-jest/package.json
- packages/mockyeah-test-mocha/package.json
- packages/mockyeah/package.json
Release branch corresponding to tag https://github.com/mockyeah/mockyeah/releases/tag/v0.24.0-alpha.0
```console
$ lerna version preminor
```
```console
$ NPM_CONFIG_OTP=XXXXXX lerna publish from-git --npm-tag next
```
> v0.24.0-alpha.0

- packages/mockyeah/test/integration/RecordAndPlayAdminServerTest.js
- packages/mockyeah/test/integration/RecordAndPlayTest.js
- packages/mockyeah/test/integration/RecordBadFilenameTest.js
- packages/mockyeah/test/integration/RecordFormatScriptFileTest.js
- packages/mockyeah/test/integration/RecordFormatScriptFunctionTest.js
- packages/mockyeah/test/integration/RecordGroupTest.js
- packages/mockyeah/test/integration/RecordGroupsTest.js
- packages/mockyeah/test/integration/RecordNothingTest.js
Looks like mocha prefers calling timeout as a function.
> test: mocha timeout as function

- packages/mockyeah/test/integration/RecordAndPlayTest.js
Just fixes some repeated paths in the record & play test.
> test: fix paths in record & play test

- lerna.json
- packages/mockyeah-cli/package.json
- packages/mockyeah-test-jest/package.json
- packages/mockyeah-test-mocha/package.json
- packages/mockyeah/package.json
Release branch corresponding to tag https://github.com/mockyeah/mockyeah/releases/tag/v0.24.0
Published off `v0` branch with:
```console
$ lerna version minor
```
```console
```
> chore(release): publish v0.24.0

- lerna.json
- packages/match-deep/package.json
- packages/mockyeah-cli/package.json
- packages/mockyeah-docker/package.json
- packages/mockyeah-docs/package.json
- packages/mockyeah-fetch/package.json
- packages/mockyeah-test-jest/package.json
- packages/mockyeah-test-mocha/package.json
- packages/mockyeah-test-server-jest/package.json
- packages/mockyeah-test-server-mocha/package.json
- packages/mockyeah-tools/package.json
- packages/mockyeah/package.json
Release branch corresponding to tag https://github.com/mockyeah/mockyeah/releases/tag/v1.0.0-alpha.0
```console
$ lerna version premajor
```
```console
```
> chore(release): publish v1.0.0-alpha.0

- lerna.json
- packages/mockyeah-cli/package.json
- packages/mockyeah-docker/package.json
Release branch corresponding to tag https://github.com/mockyeah/mockyeah/releases/tag/v1.0.0-alpha.1
```console
```
```console
```
> chore(release): publish v1.0.0-alpha.1

- package.json
Adds a top-level build command that runs with `lerna`.
> chore: add lerna build command

- package.json
- yarn.lock
> chore: lerna upgrade

- lerna.json
- packages/match-deep/package-lock.json
- packages/match-deep/package.json
- packages/mockyeah-cli/package-lock.json
- packages/mockyeah-cli/package.json
- packages/mockyeah-docker/package.json
- packages/mockyeah-docs/package-lock.json
- packages/mockyeah-docs/package.json
- packages/mockyeah-fetch/package-lock.json
- packages/mockyeah-fetch/package.json
- packages/mockyeah-test-jest/package-lock.json
- packages/mockyeah-test-jest/package.json
- packages/mockyeah-test-mocha/package-lock.json
- packages/mockyeah-test-mocha/package.json
- packages/mockyeah-test-server-jest/package-lock.json
- packages/mockyeah-test-server-jest/package.json
- packages/mockyeah-test-server-mocha/package-lock.json
- packages/mockyeah-test-server-mocha/package.json
- packages/mockyeah-tools/package-lock.json
- packages/mockyeah-tools/package.json
- packages/mockyeah/package-lock.json
- packages/mockyeah/package.json
Release branch corresponding to tag https://github.com/mockyeah/mockyeah/releases/tag/v1.0.0-alpha.3
```console
```
```console
```
> chore(release): publish v1.0.0-alpha.3

- packages/mockyeah-fetch/src/index.ts
- packages/mockyeah/app/lib/proxyRoute.js
Don't mutate response headers.
> fix(fetch): don't mutate response headers

- lerna.json
- packages/match-deep/package-lock.json
- packages/match-deep/package.json
- packages/mockyeah-cli/package-lock.json
- packages/mockyeah-cli/package.json
- packages/mockyeah-docker/package.json
- packages/mockyeah-docs/package-lock.json
- packages/mockyeah-docs/package.json
- packages/mockyeah-fetch/package-lock.json
- packages/mockyeah-fetch/package.json
- packages/mockyeah-test-jest/package-lock.json
- packages/mockyeah-test-jest/package.json
- packages/mockyeah-test-mocha/package-lock.json
- packages/mockyeah-test-mocha/package.json
- packages/mockyeah-test-server-jest/package-lock.json
- packages/mockyeah-test-server-jest/package.json
- packages/mockyeah-test-server-mocha/package-lock.json
- packages/mockyeah-test-server-mocha/package.json
- packages/mockyeah-tools/package-lock.json
- packages/mockyeah-tools/package.json
- packages/mockyeah/package-lock.json
- packages/mockyeah/package.json
Release branch corresponding to tag https://github.com/mockyeah/mockyeah/releases/tag/v1.0.0-alpha.4
```console
```
```console
```
> chore(release): publish v1.0.0-alpha.4

- packages/mockyeah-fetch/package-lock.json
- packages/mockyeah-fetch/package.json
- packages/mockyeah-fetch/src/index.ts
Add logging for use on client-side since entries are suppressed from network tab.
Fixes #470.
> feat(fetch): logging with debug

- packages/mockyeah-fetch/src/index.ts
- packages/mockyeah-fetch/src/respond.ts
- packages/mockyeah-fetch/src/types.ts
Update `@mockyeah/fetch` with more opt-in logging of any errors, each missed mock, and the full response and JSON of any matched mock.
> feat(fetch): enhance logging

- .gitignore
Simply ignore some build directories.
> chore: add more gitignores

- packages/mockyeah/package-lock.json
- packages/mockyeah/package.json
Like https://github.com/mockyeah/mockyeah/pull/496 but on `master`.
> chore: address vulns by version bumping chokidar

- packages/mockyeah/test/integration/ClosePromiseTest.js
- packages/mockyeah/test/integration/ConfigTest.js
- packages/mockyeah/test/integration/LazyStartTest.js
- packages/mockyeah/test/integration/ProxyRouteTest.js
- packages/mockyeah/test/integration/READMETest.js
- packages/mockyeah/test/integration/RecordFormatScriptFileTest.js
- packages/mockyeah/test/integration/RouteExpectationTest.js
- packages/mockyeah/test/integration/RouteProxyMethodTest.js
- packages/mockyeah/test/integration/RouteProxyNoHeadersTest.js
- packages/mockyeah/test/integration/RouteProxyTest.js
- packages/mockyeah/test/integration/RouteRegisterTest.js
- packages/mockyeah/test/integration/RouteResetTest.js
- packages/mockyeah/test/integration/StartedPromiseTest.js
- packages/mockyeah/test/integration/WatchTest.js
Handling errors in the config tests, and reducing the `setTimeout` for less non-deterministic timeout errors.
> test: more reliable

- packages/mockyeah-fetch/src/__tests__/index.test.ts
Don't proxy in tests with fake URLs otherwise tests never timeout when matching fails.
> test(fetch): no proxy in tests else infinite

- lerna.json
- packages/match-deep/package-lock.json
- packages/match-deep/package.json
- packages/mockyeah-cli/package-lock.json
- packages/mockyeah-cli/package.json
- packages/mockyeah-docker/package.json
- packages/mockyeah-docs/package-lock.json
- packages/mockyeah-docs/package.json
- packages/mockyeah-fetch-demo/package-lock.json
- packages/mockyeah-fetch-demo/package.json
- packages/mockyeah-fetch/package-lock.json
- packages/mockyeah-fetch/package.json
- packages/mockyeah-test-jest/package-lock.json
- packages/mockyeah-test-jest/package.json
- packages/mockyeah-test-mocha/package-lock.json
- packages/mockyeah-test-mocha/package.json
- packages/mockyeah-test-server-jest/package-lock.json
- packages/mockyeah-test-server-jest/package.json
- packages/mockyeah-test-server-mocha/package-lock.json
- packages/mockyeah-test-server-mocha/package.json
- packages/mockyeah-tools/package-lock.json
- packages/mockyeah-tools/package.json
- packages/mockyeah/package-lock.json
- packages/mockyeah/package.json
Release branch corresponding to tag https://github.com/mockyeah/mockyeah/releases/tag/v1.0.0-alpha.5
```console
```
```console
```
> chore(release): publish v1.0.0-alpha.5

- packages/mockyeah-fetch/src/index.ts
Should've removed this re-connect message with previous PR #520.
> fix(fetch): remove re-connect log message

- lerna.json
- packages/match-deep/package-lock.json
- packages/match-deep/package.json
- packages/mockyeah-cli/package-lock.json
- packages/mockyeah-cli/package.json
- packages/mockyeah-docker/package.json
- packages/mockyeah-docs/package-lock.json
- packages/mockyeah-docs/package.json
- packages/mockyeah-fetch-demo/package-lock.json
- packages/mockyeah-fetch-demo/package.json
- packages/mockyeah-fetch/package-lock.json
- packages/mockyeah-fetch/package.json
- packages/mockyeah-test-jest/package-lock.json
- packages/mockyeah-test-jest/package.json
- packages/mockyeah-test-mocha/package-lock.json
- packages/mockyeah-test-mocha/package.json
- packages/mockyeah-test-server-jest/package-lock.json
- packages/mockyeah-test-server-jest/package.json
- packages/mockyeah-test-server-mocha/package-lock.json
- packages/mockyeah-test-server-mocha/package.json
- packages/mockyeah-tools/package-lock.json
- packages/mockyeah-tools/package.json
- packages/mockyeah/package-lock.json
- packages/mockyeah/package.json
Release branch corresponding to tag https://github.com/mockyeah/mockyeah/releases/tag/v1.0.0-alpha.6
```console
```
```console
```
> chore(release): publish v1.0.0-alpha.6

- packages/mockyeah-docs/package-lock.json
- packages/mockyeah-docs/package.json
Otherwise it was failing with some error `Cannot find module 'ink'`.
> chore(docs): upgrade gatsby-cli

- .travis.yml
- packages/mockyeah-docs/gatsby-config.js
- packages/mockyeah-docs/package-lock.json
- packages/mockyeah-docs/package.json
Should've added the prism plugin to the mdx plugin config too.
> fix(docs): add prism to mdx

- packages/mockyeah-fetch/babel.config.js
- packages/mockyeah-fetch/package-lock.json
- packages/mockyeah-fetch/package.json
> build(fetch): add babel nullish coalescing

- packages/mockyeah-fetch-demo/src/index.ts
- packages/mockyeah-fetch-demo/src/slideshow.json
- packages/mockyeah-fetch-demo/src/slideshow.ts
- packages/mockyeah-fetch-demo/webpack.config.babel.js
Updates to the `@mockyeah/fetch` demo page in preparation for #549.
> feat(fetch-demo): updates

- .github/workflows/automerge.yml
Trying out GitHub Actions by adding this `automerge` workflow with the [`Merge pull requests` action](https://github.com/marketplace/actions/merge-pull-requests).
> chore(workflows): add automerge

- .github/workflows/semantic-pull-request.yml
Adding workflow for the [`semantic-pull-request` action](https://github.com/marketplace/actions/semantic-pull-request).
> chore(workflows): add semantic-pull-request

- .github/workflows/automerge.yml
Updating `automerge` action version.
> chore(workflows): update automerge version

- packages/mockyeah-fetch/src/__tests__/index.test.ts
- packages/mockyeah-fetch/src/parseResponseBody.ts
Add support to `@mockyeah/fetch` parsing form data as object and matching.
> feat(fetch): support matching form data as object

- lerna.json
- packages/match-deep/package-lock.json
- packages/match-deep/package.json
- packages/mockyeah-cli/package-lock.json
- packages/mockyeah-cli/package.json
- packages/mockyeah-docker/package.json
- packages/mockyeah-docs/package-lock.json
- packages/mockyeah-docs/package.json
- packages/mockyeah-fetch-demo/package-lock.json
- packages/mockyeah-fetch-demo/package.json
- packages/mockyeah-fetch/package-lock.json
- packages/mockyeah-fetch/package.json
- packages/mockyeah-test-jest/package-lock.json
- packages/mockyeah-test-jest/package.json
- packages/mockyeah-test-mocha/package-lock.json
- packages/mockyeah-test-mocha/package.json
- packages/mockyeah-test-server-jest/package-lock.json
- packages/mockyeah-test-server-jest/package.json
- packages/mockyeah-test-server-mocha/package-lock.json
- packages/mockyeah-test-server-mocha/package.json
- packages/mockyeah-tools/package-lock.json
- packages/mockyeah-tools/package.json
- packages/mockyeah-web-extension/package-lock.json
- packages/mockyeah-web-extension/package.json
- packages/mockyeah/package-lock.json
- packages/mockyeah/package.json
Release branch corresponding to tag https://github.com/mockyeah/mockyeah/releases/tag/v1.0.0-alpha.7
```console
```
```console
```
> chore(release): publish v1.0.0-alpha.7

- packages/mockyeah-fetch/src/index.ts
Initial polling loop blocking fetches to connect to dev tools (when enabled) only checked for the `__MOCKYEAH_DEVTOOLS_EXTENSION__` injected by the extension ASAP - if that times out, then we no longer block subsequent requests. If it doesn't time out so we're connected then we block until mocks from the extension have loaded, as before.
> feat(fetch): connect to web extension faster

- lerna.json
- packages/match-deep/package-lock.json
- packages/match-deep/package.json
- packages/mockyeah-cli/package-lock.json
- packages/mockyeah-cli/package.json
- packages/mockyeah-docker/package.json
- packages/mockyeah-docs/package-lock.json
- packages/mockyeah-docs/package.json
- packages/mockyeah-fetch-demo/package-lock.json
- packages/mockyeah-fetch-demo/package.json
- packages/mockyeah-fetch/package-lock.json
- packages/mockyeah-fetch/package.json
- packages/mockyeah-test-jest/package-lock.json
- packages/mockyeah-test-jest/package.json
- packages/mockyeah-test-mocha/package-lock.json
- packages/mockyeah-test-mocha/package.json
- packages/mockyeah-test-server-jest/package-lock.json
- packages/mockyeah-test-server-jest/package.json
- packages/mockyeah-test-server-mocha/package-lock.json
- packages/mockyeah-test-server-mocha/package.json
- packages/mockyeah-tools/package-lock.json
- packages/mockyeah-tools/package.json
- packages/mockyeah-web-extension/package-lock.json
- packages/mockyeah-web-extension/package.json
- packages/mockyeah/package-lock.json
- packages/mockyeah/package.json
Release branch corresponding to tag https://github.com/mockyeah/mockyeah/releases/tag/v1.0.0-alpha.8
```console
```
```console
```
> chore(release): publish v1.0.0-alpha.8

- lerna.json
- packages/match-deep/package-lock.json
- packages/match-deep/package.json
- packages/mockyeah-cli/package-lock.json
- packages/mockyeah-cli/package.json
- packages/mockyeah-docker/package.json
- packages/mockyeah-docs/package-lock.json
- packages/mockyeah-docs/package.json
- packages/mockyeah-fetch-demo/package-lock.json
- packages/mockyeah-fetch-demo/package.json
- packages/mockyeah-fetch/package-lock.json
- packages/mockyeah-fetch/package.json
- packages/mockyeah-test-jest/package-lock.json
- packages/mockyeah-test-jest/package.json
- packages/mockyeah-test-mocha/package-lock.json
- packages/mockyeah-test-mocha/package.json
- packages/mockyeah-test-server-jest/package-lock.json
- packages/mockyeah-test-server-jest/package.json
- packages/mockyeah-test-server-mocha/package-lock.json
- packages/mockyeah-test-server-mocha/package.json
- packages/mockyeah-tools/package-lock.json
- packages/mockyeah-tools/package.json
- packages/mockyeah-web-extension/package-lock.json
- packages/mockyeah-web-extension/package.json
- packages/mockyeah/package-lock.json
- packages/mockyeah/package.json
Release branch corresponding to tag https://github.com/mockyeah/mockyeah/releases/tag/v1.0.0-alpha.9
```console
```
```console
```
> chore(release): publish v1.0.0-alpha.9

- lerna.json
- packages/match-deep/package-lock.json
- packages/match-deep/package.json
- packages/mockyeah-cli/package-lock.json
- packages/mockyeah-cli/package.json
- packages/mockyeah-docker/package.json
- packages/mockyeah-docs/package-lock.json
- packages/mockyeah-docs/package.json
- packages/mockyeah-fetch-demo/package-lock.json
- packages/mockyeah-fetch-demo/package.json
- packages/mockyeah-fetch/package-lock.json
- packages/mockyeah-fetch/package.json
- packages/mockyeah-test-jest/package-lock.json
- packages/mockyeah-test-jest/package.json
- packages/mockyeah-test-mocha/package-lock.json
- packages/mockyeah-test-mocha/package.json
- packages/mockyeah-test-server-jest/package-lock.json
- packages/mockyeah-test-server-jest/package.json
- packages/mockyeah-test-server-mocha/package-lock.json
- packages/mockyeah-test-server-mocha/package.json
- packages/mockyeah-tools/package-lock.json
- packages/mockyeah-tools/package.json
- packages/mockyeah-web-extension/package-lock.json
- packages/mockyeah-web-extension/package.json
- packages/mockyeah/package-lock.json
- packages/mockyeah/package.json
Release branch corresponding to tag https://github.com/mockyeah/mockyeah/releases/tag/v1.0.0-alpha.10
```console
```
```console
```
> chore(release): publish v1.0.0-alpha.10

- packages/mockyeah-cli/bin/mockyeah-record.js
- packages/mockyeah-docs/src/pages/Packages/mockyeah-cli/index.mdx
- packages/mockyeah-docs/src/pages/Packages/mockyeah-server/Configuration.mdx
- packages/mockyeah/app/lib/proxyRecord.js
- packages/mockyeah/app/makeAPI/makeRecord.js
- packages/mockyeah/test/integration/RecordAndPlayTest.js
> feat(cli)!: separate only regex

- lerna.json
- packages/match-deep/package-lock.json
- packages/match-deep/package.json
- packages/mockyeah-cli/package-lock.json
- packages/mockyeah-cli/package.json
- packages/mockyeah-docker/package.json
- packages/mockyeah-docs/package-lock.json
- packages/mockyeah-docs/package.json
- packages/mockyeah-fetch-demo/package-lock.json
- packages/mockyeah-fetch-demo/package.json
- packages/mockyeah-fetch/package-lock.json
- packages/mockyeah-fetch/package.json
- packages/mockyeah-test-jest/package-lock.json
- packages/mockyeah-test-jest/package.json
- packages/mockyeah-test-mocha/package-lock.json
- packages/mockyeah-test-mocha/package.json
- packages/mockyeah-test-server-jest/package-lock.json
- packages/mockyeah-test-server-jest/package.json
- packages/mockyeah-test-server-mocha/package-lock.json
- packages/mockyeah-test-server-mocha/package.json
- packages/mockyeah-tools/package-lock.json
- packages/mockyeah-tools/package.json
- packages/mockyeah-web-extension/package-lock.json
- packages/mockyeah-web-extension/package.json
- packages/mockyeah/package-lock.json
- packages/mockyeah/package.json
Release branch corresponding to tag https://github.com/mockyeah/mockyeah/releases/tag/v1.0.0
```console
$ lerna version major
```
```console
```
> chore(release): publish v1.0.0

- lerna.json
- packages/match-deep/package-lock.json
- packages/match-deep/package.json
- packages/mockyeah-cli/package-lock.json
- packages/mockyeah-cli/package.json
- packages/mockyeah-docker/package-lock.json
- packages/mockyeah-docker/package.json
- packages/mockyeah-docs/package-lock.json
- packages/mockyeah-docs/package.json
- packages/mockyeah-fetch-demo/package-lock.json
- packages/mockyeah-fetch-demo/package.json
- packages/mockyeah-fetch/package-lock.json
- packages/mockyeah-fetch/package.json
- packages/mockyeah-test-jest/package-lock.json
- packages/mockyeah-test-jest/package.json
- packages/mockyeah-test-mocha/package-lock.json
- packages/mockyeah-test-mocha/package.json
- packages/mockyeah-test-server-jest/package-lock.json
- packages/mockyeah-test-server-jest/package.json
- packages/mockyeah-test-server-mocha/package-lock.json
- packages/mockyeah-test-server-mocha/package.json
- packages/mockyeah-tools/package-lock.json
- packages/mockyeah-tools/package.json
- packages/mockyeah-web-extension/package-lock.json
- packages/mockyeah-web-extension/package.json
- packages/mockyeah/package-lock.json
- packages/mockyeah/package.json
Release branch corresponding to tag https://github.com/mockyeah/mockyeah/releases/tag/v1.0.1
```console
```
```console
$ lerna publish from-package --otp XXXXXX
```
> chore(release): publish v1.0.1

- lerna.json
- packages/match-deep/package-lock.json
- packages/match-deep/package.json
- packages/mockyeah-cli/package-lock.json
- packages/mockyeah-cli/package.json
- packages/mockyeah-docker/package-lock.json
- packages/mockyeah-docker/package.json
- packages/mockyeah-docs/package-lock.json
- packages/mockyeah-docs/package.json
- packages/mockyeah-fetch-demo/package-lock.json
- packages/mockyeah-fetch-demo/package.json
- packages/mockyeah-fetch/package-lock.json
- packages/mockyeah-fetch/package.json
- packages/mockyeah-test-jest/package-lock.json
- packages/mockyeah-test-jest/package.json
- packages/mockyeah-test-mocha/package-lock.json
- packages/mockyeah-test-mocha/package.json
- packages/mockyeah-test-server-jest/package-lock.json
- packages/mockyeah-test-server-jest/package.json
- packages/mockyeah-test-server-mocha/package-lock.json
- packages/mockyeah-test-server-mocha/package.json
- packages/mockyeah-tools/package-lock.json
- packages/mockyeah-tools/package.json
- packages/mockyeah-web-extension/package-lock.json
- packages/mockyeah-web-extension/package.json
- packages/mockyeah/package-lock.json
- packages/mockyeah/package.json
Release branch corresponding to tag https://github.com/mockyeah/mockyeah/releases/tag/v1.0.2
```console
```
```console
$ lerna publish from-package --otp XXXXXX
```
> chore(release): publish v1.0.2
